/*
 * (c) Copyright 2023-2025 gradle-docker Contributors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.kineticfire.test

import groovy.json.JsonSlurper
import groovy.transform.CompileStatic

/**
 * Validator for Docker Compose state files
 * Parses and validates state JSON generated by dockerTest tasks
 */
@CompileStatic
class StateFileValidator {

    /**
     * Parse state file JSON
     */
    static Map parseStateFile(File stateFile) {
        if (!stateFile.exists()) {
            throw new FileNotFoundException("State file not found: ${stateFile.absolutePath}")
        }

        def slurper = new JsonSlurper()
        return slurper.parse(stateFile) as Map
    }

    /**
     * Validate state file has required structure
     */
    static void assertValidStructure(Map state, String expectedStackName, String expectedProjectName) {
        assert state.stackName == expectedStackName,
            "Expected stackName '${expectedStackName}', got '${state.stackName}'"

        assert state.projectName == expectedProjectName,
            "Expected projectName '${expectedProjectName}', got '${state.projectName}'"

        assert state.lifecycle != null, "Missing 'lifecycle' field"
        assert state.timestamp != null, "Missing 'timestamp' field"
        assert state.services != null, "Missing 'services' field"
        assert state.services instanceof Map, "'services' should be a map"
    }

    /**
     * Get published (host) port for a service's container port
     */
    static int getPublishedPort(Map state, String serviceName, int containerPort) {
        def service = state.services[serviceName] as Map
        if (!service) {
            throw new IllegalArgumentException("Service '${serviceName}' not found in state file")
        }

        def ports = service.publishedPorts as List<Map>
        def portMapping = ports.find { (it.container as Integer) == containerPort }

        if (!portMapping) {
            throw new IllegalArgumentException(
                "Container port ${containerPort} not found for service '${serviceName}'"
            )
        }

        return portMapping.host as Integer
    }

    /**
     * Get container ID for a service
     */
    static String getContainerId(Map state, String serviceName) {
        def service = state.services[serviceName] as Map
        if (!service) {
            throw new IllegalArgumentException("Service '${serviceName}' not found in state file")
        }
        return service.containerId as String
    }

    /**
     * Get container name for a service
     */
    static String getContainerName(Map state, String serviceName) {
        def service = state.services[serviceName] as Map
        if (!service) {
            throw new IllegalArgumentException("Service '${serviceName}' not found in state file")
        }
        return service.containerName as String
    }

    /**
     * Get all service info
     */
    static Map getServiceInfo(Map state, String serviceName) {
        def service = state.services[serviceName] as Map
        if (!service) {
            throw new IllegalArgumentException("Service '${serviceName}' not found in state file")
        }
        return service
    }

    /**
     * Get all service names
     */
    static List<String> getServiceNames(Map state) {
        return (state.services as Map).keySet().toList() as List<String>
    }
}
