services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432"

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379"

  # Spring Boot Application
  multi-service-app:
    image: verification-multi-service-app:latest
    depends_on:
      - postgres
      - redis
    ports:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 2s
      timeout: 3s
      retries: 15
      start_period: 10s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    depends_on:
      - multi-service-app
    ports:
      - "80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
