version: '3.8'
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: complexdb
      POSTGRES_USER: complexuser
      POSTGRES_PASSWORD: complexpass
    labels:
      - "test=complex-multi-file"
      - "compose-file=complex-base"
      - "tier=database"
    networks:
      - db-network
      
  cache:
    image: redis:alpine
    labels:
      - "test=complex-multi-file"
      - "compose-file=complex-base"
      - "tier=cache"
    networks:
      - cache-network

networks:
  db-network:
    driver: bridge
  cache-network:
    driver: bridge