services:
  web-app:
    ports:
      - "8084:80"
    environment:
      - NODE_ENV=production
      - API_ENDPOINT=http://api-server:8080
    labels:
      - "test=complex-multi-file"
      - "compose-file=complex-env"
      - "tier=environment"
      
  api-server:
    ports:
      - "8085:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=info
    labels:
      - "test=complex-multi-file"
      - "compose-file=complex-env"
      - "tier=environment"
      
  database:
    ports:
      - "5434:5432"
    environment:
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_SHARED_BUFFERS: 256MB
    volumes:
      - db-data:/var/lib/postgresql/data
    labels:
      - "test=complex-multi-file"
      - "compose-file=complex-env"
      - "tier=environment"

volumes:
  db-data:
    driver: local
