services:
  web-app:
    image: nginx:alpine
    labels:
      - "test=complex-multi-file"
      - "compose-file=complex-app"
      - "tier=application"
    networks:
      - app-network
      - db-network
      - cache-network
      
  api-server:
    image: time-server:latest
    environment:
      - DATABASE_URL=postgresql://complexuser:complexpass@database:5432/complexdb
    labels:
      - "test=complex-multi-file"
      - "compose-file=complex-app"
      - "tier=application"
    networks:
      - app-network
      - db-network

networks:
  app-network:
    driver: bridge
