services:
  web:
    ports:
      - "8080:80"
    environment:
      - ENV=production
    labels:
      - "test=multi-file-override"
      - "compose-file=override"
      
  cache:
    image: redis:alpine
    labels:
      - "test=multi-file-override"
      - "compose-file=override"
