version: '3.8'

services:
  dev-app:
    image: integration-test-app:latest
    container_name: gradle-docker-dev-app
    profiles: ["dev"]
    environment:
      - APP_ENV=development
      - LOG_LEVEL=INFO
      - JAVA_OPTS=-Xmx512m -Xms256m -XX:+UseContainerSupport
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    networks:
      - dev-network
    volumes:
      - dev-logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "env=development"
      - "component=gradle-docker-plugin"

  # Development database (for future enhancements)
  dev-db:
    image: postgres:15-alpine
    container_name: gradle-docker-dev-db
    profiles: ["dev", "database"]
    environment:
      - POSTGRES_DB=integration_test
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    ports:
      - "5432:5432"
    networks:
      - dev-network
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d integration_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching (development profile)
  dev-cache:
    image: redis:7-alpine
    container_name: gradle-docker-dev-cache
    profiles: ["dev", "cache"]
    ports:
      - "6379:6379"
    networks:
      - dev-network
    volumes:
      - dev-cache-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Log aggregator for monitoring profile
  log-collector:
    image: fluent/fluent-bit:latest
    container_name: gradle-docker-log-collector
    profiles: ["monitoring"]
    depends_on:
      - dev-app
    networks:
      - dev-network
    volumes:
      - dev-logs:/logs:ro
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    command: ["/fluent-bit/bin/fluent-bit", "--config=/fluent-bit/etc/fluent-bit.conf"]

networks:
  dev-network:
    driver: bridge
    name: gradle-docker-dev

volumes:
  dev-logs:
    name: gradle-docker-dev-logs
  dev-db-data:
    name: gradle-docker-dev-db
  dev-cache-data:
    name: gradle-docker-dev-cache