services:
  logs-capture-app:
    image: verification-logs-capture-app:latest
    ports:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 5s
